package controlplane

import (
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// survivorClass is deliberately the vocabulary requested by #237. "reachable"
// rows name the detector added in survivor_pool_test.go; they remain in this
// historical population so the four buckets continue to sum to the 58 operands
// measured at 1cb2af1.
type survivorClass string

const (
	reachable        survivorClass = "reachable-and-untested (closed here)"
	masked           survivorClass = "cannot-be-sole-refuser"
	unreachable      survivorClass = "unreachable-by-any-fixture"
	nondeterministic survivorClass = "cannot-be-deterministically-pinned"
)

type survivorRow struct {
	site     string
	class    survivorClass
	evidence string
	detector string
}

var controlplaneSurvivorsAt1cb2af1 = []survivorRow{
	// envelope.go — 18 survivors: 6 closed, 3 masked, 9 unreachable.
	{"envelope.go:69/op1 recipient curve", reachable, "P-384 reaches the boundary and otherwise falls through to a different ECDH diagnosis", "TestSealNamesAWrongCurveBeforeECDH"},
	{"envelope.go:73 GenerateKey error", reachable, "the key-generation collaborator can refuse entropy", "TestSealSeparatesEphemeralAndNonceEntropyFailures"},
	{"envelope.go:77 ephemeral ECDH error", unreachable, "validated P-256 private and public keys are generated by crypto/ecdh on the same curve", ""},
	{"envelope.go:81 Seal deriveKey error", unreachable, "HKDF receives fixed SHA-256 and length 32; hkdf.Key cannot reject this call", ""},
	{"envelope.go:85 Seal newGCM error", unreachable, "deriveKey returns exactly the 32-byte AES key newGCM requires", ""},
	{"envelope.go:89 nonce entropy error", reachable, "the nonce read is a distinct entropy operation after key generation", "TestSealSeparatesEphemeralAndNonceEntropyFailures"},
	{"envelope.go:100 marshal envelope error", unreachable, "Envelope contains only integers and strings, none of json.Marshal's refusing kinds", ""},
	{"envelope.go:112/op1 recipient curve", masked, "P-384 is refused by recipient.ECDH; with that error ignored, AEAD authentication still returns errOpen", ""},
	{"envelope.go:137 ephemeral base64 error", reachable, "Strict.DecodeString can return the complete point and a non-nil trailing-byte error", "TestOpenRefusesPartialBase64Results"},
	{"envelope.go:145 recipient ECDH error", unreachable, "NewPublicKey has already validated a P-256 point and recipient is validated P-256", ""},
	{"envelope.go:149/op0 nonce base64 error", reachable, "Strict.DecodeString can return all 12 nonce bytes and a non-nil trailing-byte error", "TestOpenRefusesPartialBase64Results"},
	{"envelope.go:153 ciphertext base64 error", reachable, "Strict.DecodeString can return the complete ciphertext and a non-nil trailing-byte error", "TestOpenRefusesPartialBase64Results"},
	{"envelope.go:157 Open deriveKey error", unreachable, "HKDF receives fixed SHA-256 and length 32; hkdf.Key cannot reject this call", ""},
	{"envelope.go:161 Open newGCM error", unreachable, "deriveKey returns exactly the 32-byte AES key newGCM requires", ""},
	{"envelope.go:175 AES constructor error", unreachable, "newGCM is called only with deriveKey's fixed 32-byte output", ""},
	{"envelope.go:207 PKIX parse error", masked, "the parsed-key type operand rejects the nil/non-ECDSA result; neutralising both reaches a nil dereference", ""},
	{"envelope.go:215 public ECDH conversion error", unreachable, "the value is a parsed ECDSA P-256 public key already accepted by x509 and the curve guard", ""},
	{"envelope.go:230 PKCS8 parse error", masked, "the parsed-key type operand rejects the nil/non-ECDSA result; neutralising both reaches a nil dereference", ""},

	// export.go — 35 survivors: 13 closed, 17 masked, 5 nondeterministic.
	{"export.go:136 file.Stat error", nondeterministic, "requires an opened descriptor whose Stat starts failing without a replaceable filesystem seam", ""},
	{"export.go:139 non-regular file", nondeterministic, "a directory is still refused by ReadAll; the input for which this is sole is a FIFO that hangs", ""},
	{"export.go:146 ReadAll error", nondeterministic, "requires a regular descriptor to acquire a read fault after successful open and stat", ""},
	{"export.go:149 read-growth bound", nondeterministic, "requires winning the stat/read growth race; the stat-size test intentionally cannot stand in for it", ""},
	{"export.go:161/op0 audit source", reachable, "an audit path means the configuration is not source-empty even when later structure rejects missing peers", "TestEachConfiguredJournalPreventsTheNoSourcesDiagnosis"},
	{"export.go:161/op1 policy source", reachable, "a policy path means the configuration is not source-empty even when later structure rejects missing peers", "TestEachConfiguredJournalPreventsTheNoSourcesDiagnosis"},
	{"export.go:161/op2 fencing source", reachable, "a fencing path means the configuration is not source-empty even when later structure rejects missing peers", "TestEachConfiguredJournalPreventsTheNoSourcesDiagnosis"},
	{"export.go:173 default site-version path", reachable, "a populated fixture can omit only the optional provenance path", "TestBuildCanonicalisesAnOmittedSiteVersionPath"},
	{"export.go:185 empty read path", reachable, "an omitted source becomes the not-configured marker, journal and marks together", "TestAnOmittedSourceTravelsAsNotConfiguredWithItsMarks"},
	{"export.go:230/op0 Build scan absent", masked, "verifyExport's malformed-absence guard refuses any absent entry carrying scan-worthy bytes", ""},
	{"export.go:230/op1 Build scan nonempty", masked, "verifyExport's present-empty guard refuses the only present entry this operand can newly include", ""},
	{"export.go:235 Build armedScan error", reachable, "markerShapes can be empty while a valid populated export reaches the scan", "TestBuildPropagatesAnUnarmedPayloadScan"},
	{"export.go:283 absence path", masked, "validateEntryPath immediately rejects the same empty path when the compound absence check is neutralised", ""},
	{"export.go:293/op0 present path", masked, "validateEntryPath rejects the same empty path when the compound presence check is neutralised", ""},
	{"export.go:293/op1 present digest", masked, "the recomputed-digest comparison rejects an empty recorded digest", ""},
	{"export.go:296 present empty data", reachable, "an empty fencing history with SHA-256(empty) satisfies the adjacent digest rule", "TestPresentEmptyEntryIsNotAnAbsenceMarker"},
	{"export.go:327 absent basename", reachable, "two explicit absence markers may legitimately have the same basename because neither is materialised", "TestAbsentEntriesDoNotCollideByBasename"},
	{"export.go:352/op0 audit journal present", masked, "the structural absence-marker check forbids an absent journal carrying the data needed by the other operands", ""},
	{"export.go:352/op1 audit journal nonempty", masked, "the structural present-empty check refuses the only state newly admitted by this widening", ""},
	{"export.go:355/op0 policy journal present", masked, "the structural absence-marker check forbids an absent journal carrying the data needed by the other operands", ""},
	{"export.go:355/op1 policy journal nonempty", masked, "the structural present-empty check refuses the only state newly admitted by this widening", ""},
	{"export.go:359 audit high-water JSON call", masked, "audit.VerifyIntegrity reads and refuses the same malformed high-water mark downstream", ""},
	{"export.go:362 audit shipped JSON call", masked, "audit.VerifyIntegrity reads and refuses the same malformed shipped mark downstream", ""},
	{"export.go:365 policy mark JSON call", masked, "policy.VerifyState reads and refuses the same malformed high-water mark downstream", ""},
	{"export.go:374 MkdirTemp error", reachable, "a missing TMPDIR parent makes private materialisation fail before any journal write", "TestVerifyExportNamesTemporaryDirectoryCreationFailure"},
	{"export.go:448 journal write error", reachable, "the clean absolute path / passes structure but names the temporary directory itself", "TestVerifyExportPropagatesJournalMaterialisationFailure"},
	{"export.go:452 sidecar write error", nondeterministic, "the private fresh directory and derived sidecar filenames offer no deterministic write-fault input", ""},
	{"export.go:473 sidecar JSON decode", masked, "the corresponding journal verifier reads and rejects the malformed mark downstream", ""},
	{"export.go:519 envelope Open error", masked, "the zero payload left after ignoring Open is rejected by the payload JSON decoder", ""},
	{"export.go:525 payload JSON decode", masked, "the trailing-document/version guards reject every partial or zero Export produced after a decode error", ""},
	{"export.go:550/op0 Inspect scan absent", masked, "verifyExport's malformed-absence guard refuses any absent entry carrying scan-worthy bytes", ""},
	{"export.go:550/op1 Inspect scan nonempty", masked, "verifyExport's present-empty guard refuses the only present entry this operand can newly include", ""},
	{"export.go:555 Inspect armedScan error", reachable, "markerShapes can be empty after a valid envelope has passed structural verification", "TestInspectPropagatesAnUnarmedPayloadScan"},
	{"export.go:572 summary absence", reachable, "the same report contains explicit absent and present entries", "TestSummaryLinesDistinguishesAbsenceAndBoundsItsDigest"},
	{"export.go:582 summary digest bound", reachable, "a valid 64-character digest reaches rendering", "TestSummaryLinesDistinguishesAbsenceAndBoundsItsDigest"},

	// scan.go — 5 survivors: 1 closed, 1 masked, 3 nondeterministic.
	{"scan.go:59 canary entropy error", reachable, "the package entropy boundary can return an error without terminating the process", "TestCanaryEntropyFailureCannotProduceAnArmedVerdict"},
	{"scan.go:126 empty canary probe", masked, "the only producer of an empty probe is canary's entropy-error guard; neutralising both makes the positive-control scan refuse it", ""},
	{"scan.go:190 DirEntry.Info error", nondeterministic, "requires a walk entry whose metadata lookup starts failing after WalkDir obtained it", ""},
	{"scan.go:198 bounded-read error", nondeterministic, "requires a regular file to become unreadable between metadata and the opened-descriptor read", ""},
	{"scan.go:199 disappeared-file exception", nondeterministic, "requires winning removal between WalkDir and readBounded; its fail-open direction is the separately reported contract decision", ""},
}

func TestControlplaneSurvivorLedgerReconcilesTheFreshPopulation(t *testing.T) {
	const measuredSurvivors = 58
	if len(controlplaneSurvivorsAt1cb2af1) != measuredSurvivors {
		t.Fatalf("ledger has %d rows, want the 58 survivors freshly measured at 1cb2af1", len(controlplaneSurvivorsAt1cb2af1))
	}
	want := map[survivorClass]int{reachable: 20, masked: 21, unreachable: 9, nondeterministic: 8}
	got := make(map[survivorClass]int)
	seen := make(map[string]bool)
	for _, row := range controlplaneSurvivorsAt1cb2af1 {
		if seen[row.site] {
			t.Errorf("duplicate ledger site %q", row.site)
		}
		seen[row.site] = true
		got[row.class]++
		if row.evidence == "" {
			t.Errorf("%s has no evidence", row.site)
		}
		if row.class == reachable && row.detector == "" {
			t.Errorf("%s remains reachable-and-untested: no closing detector is named", row.site)
		}
	}
	for class, count := range want {
		if got[class] != count {
			t.Errorf("%s = %d, want %d", class, got[class], count)
		}
	}
	if got[reachable]+got[masked]+got[unreachable]+got[nondeterministic] != measuredSurvivors {
		t.Fatalf("classification buckets do not sum to %d: %#v", measuredSurvivors, got)
	}
	t.Logf("fresh survivor ledger: %d reachable (all closed), %d masked, %d unreachable, %d nondeterministic",
		got[reachable], got[masked], got[unreachable], got[nondeterministic])
}

// A "reachable" row is closed only while the test it names exists. The reconciliation above checks
// that a name is present, not that it resolves: rename or delete a detector and this ledger keeps
// asserting a closure no test performs, with every count still summing to 58. So each named
// detector must be declared exactly once as a top-level test function in this package's test files.
func TestControlplaneSurvivorLedgerDetectorsAreDeclaredTests(t *testing.T) {
	files, err := filepath.Glob("*_test.go")
	if err != nil || len(files) == 0 {
		t.Fatalf("cannot enumerate this package's test files: %v (%d found)", err, len(files))
	}
	declared := make(map[string]int)
	declaration := regexp.MustCompile(`(?m)^func (Test[A-Za-z0-9_]+)\(t \*testing\.T\)`)
	for _, file := range files {
		source, err := os.ReadFile(file)
		if err != nil {
			t.Fatal(err)
		}
		for _, match := range declaration.FindAllSubmatch(source, -1) {
			declared[string(match[1])]++
		}
	}
	named := 0
	for _, row := range controlplaneSurvivorsAt1cb2af1 {
		if row.detector == "" {
			continue
		}
		named++
		if declared[row.detector] != 1 {
			t.Errorf("%s names detector %s, declared %d times in this package's tests", row.site, row.detector, declared[row.detector])
		}
	}
	// A regexp that stopped matching would find no declarations and fail every row above; an empty
	// ledger would check nothing and pass. Refuse the second as loudly as the first.
	if named == 0 {
		t.Fatal("no row names a detector, so this check verified nothing")
	}
}
