"""deploy/baremetal/initrd_drift.py and e2e/initrd-drift.sh (#198): the daily report of what moved in the
initrd since its inventory was reviewed."""
import pathlib
import re
import unittest

from deploy.baremetal import initrd_drift

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = [
    "ours regalia-kms f 0755 0:0 usr/bin/regalia-unlock =compiled",
    "generated dracut f 0644 0:0 etc/initrd-release " + "a" * 64,
    "package udev=257.13-1 f 0644 0:0 usr/lib/udev/rules.d/60-block.rules " + "b" * 64,
    "package libssl3t64=3.5.1-1 f 0644 0:0 usr/lib/x86_64-linux-gnu/libssl.so.3 " + "c" * 64,
]


def parsed(lines):
    return initrd_drift.parse(lines)


class Report(unittest.TestCase):
    def test_nothing_moved_is_no_report(self):
        self.assertEqual(initrd_drift.report(parsed(BASE), parsed(BASE)), (False, ""))
        # the client follows the repository, not the archive: it is never drift
        self.assertEqual(initrd_drift.report(parsed(BASE), parsed(BASE[:1] + BASE[1:])), (False, ""))

    def test_a_package_update_is_named_and_a_security_fix_is_marked(self):
        today = BASE[:3] + ["package libssl3t64=3.5.1-1+deb13u1 f 0644 0:0 usr/lib/x86_64-linux-gnu/libssl.so.3 " + "d" * 64]
        changed, body = initrd_drift.report(parsed(BASE), parsed(today), {"libssl3t64": "3.5.1-1+deb13u1"})
        self.assertTrue(changed)
        self.assertIn("| libssl3t64 | 3.5.1-1 | 3.5.1-1+deb13u1 | **3.5.1-1+deb13u1** |", body)
        self.assertIn("A package of the inventory has a security update", body)
        self.assertIn("`usr/lib/x86_64-linux-gnu/libssl.so.3` changed (libssl3t64=3.5.1-1+deb13u1)", body)
        # without the security archive's word, the update is listed and not marked
        _, plain = initrd_drift.report(parsed(BASE), parsed(today))
        self.assertNotIn("security update", plain)

    def test_generated_lines_are_shown_whole_for_the_reader(self):
        today = BASE[:1] + ["generated dracut f 0644 0:0 etc/initrd-release " + "e" * 64] + BASE[2:] + \
            ["generated dracut f 0755 0:0 var/lib/dracut/hooks/pre-mount/10-new.sh " + "f" * 64]
        changed, body = initrd_drift.report(parsed(BASE), parsed(today))
        self.assertTrue(changed)
        self.assertIn("### Generated by dracut (2): read these", body)
        self.assertIn("- generated dracut f 0644 0:0 etc/initrd-release " + "a" * 64, body)
        self.assertIn("+ generated dracut f 0644 0:0 etc/initrd-release " + "e" * 64, body)
        self.assertIn("+ generated dracut f 0755 0:0 var/lib/dracut/hooks/pre-mount/10-new.sh", body)

    def test_the_same_findings_give_the_same_digest(self):
        today = BASE[:2] + ["package udev=257.14-1 f 0644 0:0 usr/lib/udev/rules.d/60-block.rules " + "9" * 64] + BASE[3:]
        one = initrd_drift.report(parsed(BASE), parsed(today))[1]
        two = initrd_drift.report(parsed(BASE), parsed(today))[1]
        self.assertEqual(one, two)
        self.assertRegex(one, r"<!-- initrd-drift [0-9a-f]{16} -->\n$")

    def test_a_line_that_is_not_an_inventory_line_is_refused(self):
        with self.assertRaises(ValueError):
            initrd_drift.parse(["usr/lib/x sha256:00"])

    def test_the_security_archive_s_versions_are_read_from_its_packages_file(self):
        text = "Package: libssl3t64\nVersion: 3.5.1-1+deb13u1\nArchitecture: amd64\n\nPackage: udev\nVersion: 257.13-1+deb13u1\n"
        self.assertEqual(initrd_drift.security_versions(text), {"libssl3t64": "3.5.1-1+deb13u1", "udev": "257.13-1+deb13u1"})


class Script(unittest.TestCase):
    def test_the_drift_build_uses_the_packages_the_boot_test_uses(self):
        """Otherwise every day's report would show the difference between two package lists, not drift."""
        boot = (ROOT / "e2e" / "unlock-boot-qemu.sh").read_text()
        drift = (ROOT / "e2e" / "initrd-drift.sh").read_text()
        included = re.search(r"--include=(\S+) \\", boot).group(1)
        self.assertEqual(re.search(r"^INCLUDE=(\S+)$", drift, re.M).group(1), included)
        self.assertIn("--no-hostonly --no-hostonly-cmdline --add regalia-unlock", drift)
        self.assertIn("$SUITE-security", drift)

    def test_the_workflow_keeps_one_issue_and_writes_nothing_else(self):
        workflow = (ROOT / ".github" / "workflows" / "initrd-drift.yml").read_text()
        self.assertIn("issues: write", workflow)
        self.assertNotIn("contents: write", workflow)
        self.assertIn("--label initrd-drift", workflow)
        self.assertIn("--body-file", workflow)


if __name__ == "__main__":
    unittest.main()
