"""deploy/baremetal/initrd_drift.py and e2e/initrd-drift.sh (#198): the daily report of what moved in the
initrd since its inventory was reviewed."""
import pathlib
import re
import unittest

from deploy.baremetal import initrd_drift

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = [
    "ours regalia-kms f 0755 0:0 usr/bin/regalia-unlock =compiled",
    "generated dracut f 0644 0:0 etc/initrd-release " + "a" * 64,
    "package udev=257.13-1 f 0644 0:0 usr/lib/udev/rules.d/60-block.rules " + "b" * 64,
    "package libssl3t64=3.5.1-1 f 0644 0:0 usr/lib/x86_64-linux-gnu/libssl.so.3 " + "c" * 64,
]


def parsed(lines):
    return initrd_drift.parse(lines)


class Report(unittest.TestCase):
    def test_nothing_moved_is_no_report(self):
        self.assertEqual(initrd_drift.report(parsed(BASE), parsed(BASE)), (False, ""))
        # the client follows the repository, not the archive: it is never drift
        self.assertEqual(initrd_drift.report(parsed(BASE), parsed(BASE[:1] + BASE[1:])), (False, ""))

    def test_a_package_update_is_named_and_a_security_fix_is_marked(self):
        today = BASE[:3] + ["package libssl3t64=3.5.1-1+deb13u1 f 0644 0:0 usr/lib/x86_64-linux-gnu/libssl.so.3 " + "d" * 64]
        changed, body = initrd_drift.report(parsed(BASE), parsed(today), {"libssl3t64": "3.5.1-1+deb13u1"})
        self.assertTrue(changed)
        self.assertIn(r"| libssl3t64 | 3\.5\.1\-1 | 3\.5\.1\-1\+deb13u1 | **3\.5\.1\-1\+deb13u1** |", body)
        self.assertIn("A package of the inventory has a security update", body)
        self.assertIn(r"usr/lib/x86\_64\-linux\-gnu/libssl\.so\.3 changed (libssl3t64=3\.5\.1\-1\+deb13u1)", body)
        # without the security archive's word, the update is listed and not marked
        _, plain = initrd_drift.report(parsed(BASE), parsed(today))
        self.assertNotIn("security update", plain)

    def test_generated_lines_are_shown_whole_for_the_reader(self):
        today = BASE[:1] + ["generated dracut f 0644 0:0 etc/initrd-release " + "e" * 64] + BASE[2:] + \
            ["generated dracut f 0755 0:0 var/lib/dracut/hooks/pre-mount/10-new.sh " + "f" * 64]
        changed, body = initrd_drift.report(parsed(BASE), parsed(today))
        self.assertTrue(changed)
        self.assertIn("### Generated by dracut (2): read these", body)
        self.assertIn("- generated dracut f 0644 0:0 etc/initrd-release " + "a" * 64, body)
        self.assertIn("+ generated dracut f 0644 0:0 etc/initrd-release " + "e" * 64, body)
        self.assertIn("+ generated dracut f 0755 0:0 var/lib/dracut/hooks/pre-mount/10-new.sh", body)

    def test_archive_data_is_inert_markdown(self):
        """Package names, versions and paths come from the archive: none of them may link, mention, format,
        break the table or close the code fence."""
        hostile = "package evil|pkg=1.0<img/src=x>@owner f 0644 0:0 usr/lib/[x](http://e)`` " + "1" * 64
        changed, body = initrd_drift.report(parsed(BASE), parsed(BASE + [hostile, "generated dracut f 0644 0:0 etc/``` " + "2" * 64]))
        self.assertTrue(changed)
        for raw in ("<img", "@owner", "[x](http://e)", "evil|pkg"):
            self.assertNotIn(raw, body)
        self.assertIn(r"evil\|pkg", body)
        self.assertIn("&lt;img/src=x&gt;", body)
        fence = body[body.index("```\n") + 4:]
        self.assertNotIn("`", fence[:fence.index("\n```")])           # nothing inside can close the fence

    def test_a_fence_and_a_mention_in_a_generated_line_stay_inside_the_block(self):
        line = "generated dracut f 0644 0:0 etc/x" + "`" * 3 + "@digital-frontier-lda/x " + "3" * 64
        changed, body = initrd_drift.report(parsed(BASE), parsed(BASE + [line]))
        self.assertTrue(changed)
        block = body[body.index("`" * 3 + "\n") + 4:]
        block = block[:block.index("\n" + "`" * 3)]
        self.assertNotIn("`", block)
        self.assertIn("etc/x" + "'" * 3 + "@digital-frontier-lda/x", block)      # inside a code block: no notification
        self.assertNotIn("@digital-frontier-lda", body.replace(block, ""))

    def test_the_same_findings_give_the_same_digest(self):
        today = BASE[:2] + ["package udev=257.14-1 f 0644 0:0 usr/lib/udev/rules.d/60-block.rules " + "9" * 64] + BASE[3:]
        one = initrd_drift.report(parsed(BASE), parsed(today))[1]
        two = initrd_drift.report(parsed(BASE), parsed(today))[1]
        self.assertEqual(one, two)
        self.assertRegex(one, r"<!-- initrd-drift [0-9a-f]{16} -->\n$")

    def test_a_line_that_is_not_an_inventory_line_is_refused(self):
        with self.assertRaises(ValueError):
            initrd_drift.parse(["usr/lib/x sha256:00"])

    def test_the_security_archive_s_versions_are_read_from_its_packages_file(self):
        text = "Package: libssl3t64\nVersion: 3.5.1-1+deb13u1\nArchitecture: amd64\n\nPackage: udev\nVersion: 257.13-1+deb13u1\n"
        self.assertEqual(initrd_drift.security_versions(text), {"libssl3t64": "3.5.1-1+deb13u1", "udev": "257.13-1+deb13u1"})


class Script(unittest.TestCase):
    def test_the_drift_build_uses_the_packages_the_boot_test_uses(self):
        """Otherwise every day's report would show the difference between two package lists, not drift."""
        boot = (ROOT / "e2e" / "unlock-boot-qemu.sh").read_text()
        drift = (ROOT / "e2e" / "initrd-drift.sh").read_text()
        included = re.search(r"--include=(\S+) \\", boot).group(1)
        self.assertEqual(re.search(r"^INCLUDE=(\S+)$", drift, re.M).group(1), included)
        self.assertIn("--no-hostonly --no-hostonly-cmdline --add regalia-unlock", drift)
        self.assertIn("$SUITE-security", drift)

    def test_the_workflow_splits_building_from_filing(self):
        import yaml
        text = (ROOT / ".github" / "workflows" / "initrd-drift.yml").read_text()
        workflow = yaml.safe_load(text)
        triggers = workflow.get(True, workflow.get("on"))           # YAML 1.1 reads the key `on` as True
        self.assertEqual(sorted(triggers), ["pull_request", "schedule", "workflow_dispatch"])
        self.assertNotIn("pull_request_target", text)
        self.assertEqual(workflow["permissions"], {"contents": "read"})
        build, file_ = workflow["jobs"]["build"], workflow["jobs"]["file"]
        # what runs archive code (as root) holds a token that can write nothing
        self.assertEqual(build["permissions"], {"contents": "read"})
        self.assertIn("initrd-drift.sh", " ".join(s.get("run", "") for s in build["steps"]))
        # what can write issues runs no checkout and nothing from the archive: it downloads the report and calls gh
        self.assertEqual(file_["permissions"], {"issues": "write"})
        self.assertEqual(file_["needs"], "build")
        self.assertEqual(file_["if"], "always() && github.event_name != 'pull_request'")
        self.assertTrue(file_["steps"][0]["continue-on-error"])
        self.assertEqual([s.get("uses", "").split("@")[0] for s in file_["steps"]], ["actions/download-artifact", ""])
        filing = file_["steps"][1]["run"]
        self.assertNotIn("checkout", filing)
        self.assertNotIn("bash ", filing)
        # one issue: labelled AND opened by this workflow; a rerun edits it; a failed check says so
        self.assertIn("gh issue list --state open --label initrd-drift --author 'app/github-actions'", filing)
        self.assertIn("gh issue edit", filing)
        self.assertIn("The initrd drift check FAILED", filing)
        self.assertIn("--body-file", filing)
        self.assertEqual(workflow["concurrency"]["group"], "initrd-drift")

    def test_the_security_list_is_the_one_apt_verified(self):
        script = (ROOT / "e2e" / "initrd-drift.sh").read_text()
        self.assertNotIn("urlopen", script)
        self.assertIn('/var/lib/apt/lists/*_dists_"$SUITE"-security_main_binary-amd64_Packages', script)
        self.assertEqual(script.count("[signed-by=$KEYRING]"), 3)
        self.assertIn("e2e/lib/debian-keyring.sh", script)
        self.assertIn("--skip=cleanup/apt/lists", script)

if __name__ == "__main__":
    unittest.main()
