package audit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A JOURNAL WRITTEN BEFORE verified_approvers EXISTED MUST STILL VERIFY.
//
// Event hashes cover json.Marshal of the whole struct, so ANY change to the marshalled byte
// stream makes every previously written event fail Verify. RBACDigest did exactly that, and
// TestVerifyRefusesPreRBACDigestEvents pins it as a deliberate upgrade-day cost.
//
// TestAnEventWithoutApproversMarshalsWithoutTheField asserts that verified_approvers is omitted
// when empty. That is NECESSARY BUT NOT SUFFICIENT for "existing journals keep verifying", and
// the difference is not pedantic. Add the next field without omitempty --
//
//	VerifiedApprovers []string `json:"verified_approvers,omitempty"`
//	SiteID            string   `json:"site_id"`
//
// -- and that test still passes while every journal in existence becomes unverifiable. Measured,
// not supposed. It is also the exact mistake RBACDigest already made once.
//
// THE FIXTURE IS A PASTED LITERAL ON PURPOSE. A journal generated by the current code cannot
// detect a change in the current code: it would move along with the struct and agree with itself
// forever. That is the same self-referential trap as a verifier whose search space includes the
// artifact it is checking. These bytes were emitted by the audit package at the commit before
// verified_approvers existed; the device identifier was neutralised for public release and the
// chain recomputed once at that time. Do not regenerate them again.
const preChangeJournal = `
{"sequence":1,"timestamp":"2026-09-04T12:00:00Z","request_id":"018f0000-0000-7000-8000-00000000000a","principal":"spiffe://regalia/workload/sops-prod","decision":"allow","object_id":"production-sops","purpose":"sops-data-key","operation":"sign","device_id":"hsm-sitea","outcome":"success","latency_ms":10,"registry_digest":"sha256:aa","policy_digest":"sha256:bb","rbac_digest":"sha256:cc","previous_hash":"sha256:0000000000000000000000000000000000000000000000000000000000000000","hash":"sha256:75acfe5510d811d95bfcf3cc345b53fc43b06a7fe2e8ad3dd74587dca958bcdd"}
{"sequence":2,"timestamp":"2026-09-04T12:00:01Z","request_id":"018f0000-0000-7000-8000-00000000000b","principal":"spiffe://regalia/workload/sops-prod","decision":"allow","object_id":"production-sops","purpose":"sops-data-key","operation":"unwrap","device_id":"hsm-sitea","outcome":"success","latency_ms":11,"registry_digest":"sha256:aa","policy_digest":"sha256:bb","rbac_digest":"sha256:cc","previous_hash":"sha256:75acfe5510d811d95bfcf3cc345b53fc43b06a7fe2e8ad3dd74587dca958bcdd","hash":"sha256:51f7988b4c2974158325c045caa8ec912d58fcf35cc9caafc75ba75331eb1f59"}
{"sequence":3,"timestamp":"2026-09-04T12:00:02Z","request_id":"018f0000-0000-7000-8000-00000000000c","principal":"spiffe://regalia/workload/sops-prod","decision":"allow","object_id":"production-sops","purpose":"sops-data-key","operation":"certificate-sign","device_id":"hsm-sitea","outcome":"success","latency_ms":12,"registry_digest":"sha256:aa","policy_digest":"sha256:bb","rbac_digest":"sha256:cc","previous_hash":"sha256:51f7988b4c2974158325c045caa8ec912d58fcf35cc9caafc75ba75331eb1f59","hash":"sha256:43ecdb159b0fdaa593321564bc73c2e45efc503b0121c4e97177882868729b4f"}
`

func TestAJournalWrittenBeforeVerifiedApproversStillVerifies(t *testing.T) {
	path := filepath.Join(t.TempDir(), "audit.jsonl")
	contents := strings.TrimLeft(preChangeJournal, "\n")
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}

	// The fixture must be what it claims to be. A "pre-change" journal that somehow carried the
	// field would make the assertion below hold for the wrong reason, forever.
	if strings.Contains(contents, "verified_approvers") {
		t.Fatal("the pre-change fixture carries verified_approvers, so it is not pre-change and this test proves nothing")
	}

	events, err := Verify(path)
	if err != nil {
		t.Fatalf("a journal written before verified_approvers existed no longer verifies: %v\n"+
			"Every journal an operator holds is now unverifiable. If a field was added, it needs omitempty.", err)
	}
	if len(events) != 3 {
		t.Fatalf("verified %d events, want 3", len(events))
	}
}
