#!/usr/bin/env python3
"""Which SSH host is which KMS node: an administrator's known_hosts, generated from the membership
manifest (#143; SSH.md).

A v2 manifest pins each node's SSH host key (`ssh_host_pub`, membership.py). Trust in a host key then
comes from the offline membership root, not from the first connection, and it is revoked the way every
other node identity is: by the manifest that retires the node.

    python3 -Es -m deploy.baremetal.ssh_trust --chain chain.json --root-key <64 hex> --at-least-epoch 7 \\
        --known-hosts ~/.ssh/regalia_known_hosts [--addresses addresses.json --ssh-config ~/.ssh/regalia_config]

known_hosts(manifest) gives:

    a ssh-ed25519 AAAA... regalia-kms epoch 7 ACTIVE          one line per node that is not retired
    @revoked * ssh-ed25519 AAAA... regalia-kms epoch 7 c RETIRED      and one per retired node that had a key

THE HOST NAME IS THE NODE ID, not an address. The administrator's ssh is told `HostKeyAlias <node_id>`
(ssh_config() writes that), so the key that answers at an address is checked against the node the
administrator MEANT, and a node cannot answer for another: its key is filed under its own name only.
A retired node's key is `@revoked` for every name. A node retired before it had a key on record has no
line: it was never trusted here, and nothing is invented for it.

The file is used ALONE: ssh_config() sets UserKnownHostsFile to it, GlobalKnownHostsFile to /dev/null,
StrictHostKeyChecking yes, and UpdateHostKeys no (a host must not be able to add keys to it). It sets them
for EVERY name, in a closing `Host *` block: a retired node, a node with no address given, or a bare IP
address has no block of its own, and without the catch-all ssh would fall back to its defaults for it
(the user's own known_hosts, a trust-on-first-use prompt) exactly when a node has just been revoked.
So the generated file is for `ssh -F <file>` only. Included from ~/.ssh/config its `Host *` would apply
to every host the user connects to.

ROLLBACK. A node's Store checks its chain against its TPM. An administrator's workstation has no such
anchor, so current() takes the chain AND the lowest epoch the administrator will accept: the epoch of
the last manifest they saw, or of the revocation they are acting on. An older chain, on which a retired
node is still listed as live, is refused. There is no default. The program also never goes back by
itself: the known_hosts in place records the epoch and manifest it was generated from, and a chain that
ends below that epoch, or does not hold that manifest at that epoch, does not replace it. A file in the
way that this program did not write is not replaced either. THE FILE IN PLACE IS THE ONLY MEMORY: once
it is moved away or deleted, --at-least-epoch is the only floor again.
"""
import argparse
import base64
import ipaddress
import os
import re
import sys
import tempfile

from deploy.baremetal import membership

Refused, require = membership.Refused, membership.require

KEY_TYPE = "ssh-ed25519"
HEADER = "# Generated by deploy/baremetal/ssh_trust.py from membership epoch %d, manifest %s. Do not edit by hand."
_HEADER = re.compile(r"# Generated by deploy/baremetal/ssh_trust\.py from membership epoch ([1-9][0-9]{0,18}), manifest ([0-9a-f]{64})\. Do not edit by hand\.")
_BLOB_PREFIX = len(KEY_TYPE).to_bytes(4, "big") + KEY_TYPE.encode() + (32).to_bytes(4, "big")


def host_key(ssh_host_pub):
    """The OpenSSH form of a manifest's ssh_host_pub: "ssh-ed25519 <base64>"."""
    membership.hex_field(ssh_host_pub, 64, "ssh_host_pub")
    return "%s %s" % (KEY_TYPE, base64.b64encode(_BLOB_PREFIX + bytes.fromhex(ssh_host_pub)).decode())


def raw_host_key(line):
    """The manifest form (64 hex) of an OpenSSH Ed25519 public key line, as in ssh_host_ed25519_key.pub:
    "ssh-ed25519 <base64> [comment]". Any other key type or length is refused. (51 bytes are 68 base64
    characters with no padding, so one key has one spelling.)"""
    require(isinstance(line, str), "an SSH public key is a line of text")
    fields = line.split()
    require(len(fields) >= 2 and fields[0] == KEY_TYPE, "the SSH host key must be %s" % KEY_TYPE)
    try:
        blob = base64.b64decode(fields[1], validate=True)
    except ValueError:
        raise Refused("the SSH host key is not base64")
    require(len(blob) == len(_BLOB_PREFIX) + 32 and blob.startswith(_BLOB_PREFIX), "the SSH host key is not a canonical %s key" % KEY_TYPE)
    return blob[len(_BLOB_PREFIX):].hex()


def known_hosts(manifest):
    """The known_hosts text for a v2 manifest (see the module docstring). Deterministic."""
    nodes = membership.validate(manifest)
    require(manifest["schema"] in membership.SCHEMAS[1:], "a %s manifest names no SSH host keys: the chain must have moved to %s"
            % (manifest["schema"], membership.SCHEMA_V2))
    note = "regalia-kms epoch %d" % manifest["epoch"]
    lines = [HEADER % (manifest["epoch"], membership.digest(manifest))]
    for node_id in sorted(nodes):
        node = nodes[node_id]
        if node["state"] not in membership.TERMINAL:
            lines.append("%s %s %s %s" % (node_id, host_key(node["ssh_host_pub"]), note, node["state"]))
    for node_id in sorted(nodes):
        node = nodes[node_id]
        if node["state"] in membership.TERMINAL and "ssh_host_pub" in node:
            lines.append("@revoked * %s %s %s %s" % (host_key(node["ssh_host_pub"]), note, node_id, node["state"]))
    return "\n".join(lines) + "\n"


def _plain_path(path, label):
    # an ssh_config value: no spaces, quotes, tokens (%h) or ~ expansion to reason about
    require(isinstance(path, str) and re.fullmatch(r"/[A-Za-z0-9_./-]{1,255}", path) is not None and "/../" not in path + "/",
            "%s must be an absolute path of letters, digits and . _ - /" % label)


def ssh_config(manifest, addresses, known_hosts_path, port=22):
    """An ssh_config file for `ssh -F`: one `Host <node_id>` per node that is not retired and has an address
    in `addresses` ({node_id: IPv4 address}; the manifest holds no addresses), checked against the generated
    known_hosts only, under the node's own name; and a closing `Host *`, so that every OTHER name is held
    to the same file and the same strictness instead of ssh's defaults."""
    nodes = membership.validate(manifest)
    require(manifest["schema"] in membership.SCHEMAS[1:], "a %s manifest names no SSH host keys" % manifest["schema"])
    _plain_path(known_hosts_path, "the known_hosts path")
    require(isinstance(port, int) and not isinstance(port, bool) and 1 <= port <= 65535, "the SSH port must be 1 to 65535")
    require(isinstance(addresses, dict), "addresses must map node IDs to IPv4 addresses")
    for node_id, address in addresses.items():
        require(node_id in nodes, "%r has an address but is not in the manifest" % (node_id,))
        require(nodes[node_id]["state"] not in membership.TERMINAL, "%s is %s: it gets no ssh_config entry" % (node_id, nodes[node_id]["state"]))
        try:
            require(str(ipaddress.IPv4Address(address)) == address, "the address of %s must be a plain IPv4 address" % node_id)
        except ValueError:
            raise Refused("the address of %s must be a plain IPv4 address" % node_id)
    require(len(set(addresses.values())) == len(addresses), "two nodes cannot have one address")
    strict = ["    HostKeyAlgorithms %s" % KEY_TYPE,
              "    UserKnownHostsFile %s" % known_hosts_path,
              "    GlobalKnownHostsFile /dev/null",
              "    StrictHostKeyChecking yes",
              "    UpdateHostKeys no",
              "    CheckHostIP no",
              "    ForwardAgent no"]
    out = [HEADER % (manifest["epoch"], membership.digest(manifest)),
           "# For `ssh -F <this file>` only. Never Include it: the last block applies to every host."]
    for node_id in sorted(addresses):
        out += ["Host %s" % node_id, "    HostName %s" % addresses[node_id], "    Port %d" % port, "    HostKeyAlias %s" % node_id] + strict
    # Every other name: a retired node, a node without an address here, an IP address. None has a host line
    # in the generated known_hosts, so each is refused, and a retired node's key is reported as REVOKED.
    out += ["Host *"] + strict
    return "\n".join(out) + "\n"


def verified(envelopes, root_key, at_least_epoch):
    """(the newest manifest, the manifest digest at every epoch) of a whole chain, verified from the pinned
    root at epoch 1, and refused if it ends below `at_least_epoch` (the rollback check a workstation has
    instead of a TPM)."""
    require(isinstance(at_least_epoch, int) and not isinstance(at_least_epoch, bool) and at_least_epoch >= 1, "at_least_epoch must be an integer >= 1")
    require(isinstance(envelopes, list) and envelopes, "a chain is a non-empty list of envelopes")
    manifest, digests = None, []
    for envelope in envelopes:
        nxt = membership.accept(manifest, envelope, root_key)
        require(nxt is not manifest, "the chain repeats epoch %d" % nxt["epoch"])
        digests.append(membership.digest(nxt))
        manifest = nxt
    require(manifest["epoch"] >= at_least_epoch, "ROLLBACK: the chain ends at epoch %d and at least epoch %d is expected: "
            "fetch the current chain" % (manifest["epoch"], at_least_epoch))
    return manifest, digests


def current(envelopes, root_key, at_least_epoch):
    """The newest manifest of a verified chain (see verified())."""
    return verified(envelopes, root_key, at_least_epoch)[0]


def generated_from(path):
    """(epoch, manifest digest) from the first line of a file this program wrote; None if no file is there.
    A file that is there and does not start with that line is refused: it is somebody else's, or damaged,
    and it is not replaced."""
    try:
        with open(path, "rb") as f:
            first = f.readline(512)
    except FileNotFoundError:
        # a symbolic link that points nowhere is not "no file": something was put there
        require(not os.path.islink(path), "%s is a symbolic link to nothing: it is not replaced (remove it first)" % path)
        return None
    found = _HEADER.fullmatch(first.decode("ascii", "replace").rstrip("\n"))
    require(found is not None, "%s exists and was not generated by this program: it is not replaced. Moving it away removes the "
            "only record of the epoch it came from: --at-least-epoch is then the only floor" % path)
    return int(found.group(1)), found.group(2)


def _not_older(path, digests):
    """The file in place at `path`, if any, must come from this chain: from its newest manifest or from an
    older epoch OF IT. `digests` is the chain's manifest digest at each epoch."""
    was = generated_from(path)
    if was is None:
        return
    require(len(digests) >= was[0], "ROLLBACK: %s was generated from epoch %d and the chain given ends at epoch %d: an older "
            "chain does not replace it" % (path, was[0], len(digests)))
    require(digests[was[0] - 1] == was[1], "CONFLICT: %s was generated from another manifest at epoch %d than the chain given holds: "
            "two manifests were signed for one epoch; record an incident" % (path, was[0]))


def _stage(path, text):
    """`text` in a finished temporary file beside `path` (0600, flushed to disk); returns its name."""
    directory = os.path.dirname(os.path.abspath(path))
    fd, tmp = tempfile.mkstemp(prefix=".regalia-ssh-", dir=directory)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp, 0o600)
    except BaseException:
        os.unlink(tmp)
        raise
    return tmp


def _write(files):
    """Replace each (path, text) atomically, and none unless every one could be staged: a refusal or a
    missing directory for the second file leaves the first as it was."""
    staged = []
    try:
        for path, text in files:
            staged.append((_stage(path, text), path))
        while staged:
            os.replace(*staged[0])                 # the mkstemp name is replaced over the target, never written through it
            staged.pop(0)
    finally:
        for tmp, _ in staged:
            if os.path.exists(tmp):
                os.unlink(tmp)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--chain", required=True, help="the whole membership chain (a JSON list of envelopes, as Store keeps it)")
    ap.add_argument("--root-key", required=True, help="the pinned membership root key, 64 hex")
    ap.add_argument("--at-least-epoch", required=True, type=int, help="refuse a chain that ends below this epoch")
    ap.add_argument("--known-hosts", required=True, help="where to write the known_hosts file")
    ap.add_argument("--addresses", help="a JSON object {node_id: IPv4 address}; needed for --ssh-config")
    ap.add_argument("--ssh-config", help="where to write the ssh_config fragment")
    ap.add_argument("--port", type=int, default=22)
    args = ap.parse_args(argv)
    try:
        require((args.addresses is None) == (args.ssh_config is None), "--addresses and --ssh-config go together")
        with open(args.chain, "rb") as f:
            chain = membership.load(f.read(membership.MAX_CHAIN_BYTES + 1), limit=membership.MAX_CHAIN_BYTES)
        manifest, digests = verified(chain, args.root_key, args.at_least_epoch)
        hosts = known_hosts(manifest)
        config = None
        if args.ssh_config:
            with open(args.addresses, "rb") as f:
                addresses = membership.load(f.read(membership.MAX_BYTES + 1))
            config = ssh_config(manifest, addresses, os.path.abspath(args.known_hosts), args.port)
        _not_older(args.known_hosts, digests)
        if config is not None:
            require(os.path.realpath(args.known_hosts) != os.path.realpath(args.ssh_config), "--known-hosts and --ssh-config name the same file")
            _not_older(args.ssh_config, digests)
        # nothing is written unless everything was accepted and every file could be staged
        _write([(args.known_hosts, hosts)] + ([(args.ssh_config, config)] if config is not None else []))
    except (OSError, Refused) as failure:
        print("ssh_trust: %s" % failure, file=sys.stderr)
        return 1
    lines = hosts.splitlines()[1:]
    revoked = sum(1 for line in lines if line.startswith("@revoked"))
    print("ssh_trust: epoch %d, manifest %s: %d host(s), %d revoked key(s)"
          % (manifest["epoch"], membership.digest(manifest), len(lines) - revoked, revoked))
    return 0


if __name__ == "__main__":
    sys.exit(main())
