#!/usr/bin/env python3
"""Which SSH host is which KMS node: an administrator's known_hosts, generated from the membership
manifest (#143; SSH.md).

A v2 manifest pins each node's SSH host key (`ssh_host_pub`, membership.py). Trust in a host key then
comes from the offline membership root, not from the first connection, and it is revoked the way every
other node identity is: by the manifest that retires the node.

    python3 -Es -m deploy.baremetal.ssh_trust --chain chain.json --root-key <64 hex> --at-least-epoch 7 \\
        --known-hosts ~/.ssh/regalia_known_hosts [--addresses addresses.json --ssh-config ~/.ssh/regalia_config]

known_hosts(manifest) gives:

    a ssh-ed25519 AAAA... regalia-kms epoch 7 ACTIVE          one line per node that is not retired
    @revoked * ssh-ed25519 AAAA... regalia-kms epoch 7 c RETIRED      and one per retired node that had a key

THE HOST NAME IS THE NODE ID, not an address. The administrator's ssh is told `HostKeyAlias <node_id>`
(ssh_config() writes that), so the key that answers at an address is checked against the node the
administrator MEANT, and a node cannot answer for another: its key is filed under its own name only.
A retired node's key is `@revoked` for every name. A node retired before it had a key on record has no
line: it was never trusted here, and nothing is invented for it.

The file is used ALONE: ssh_config() sets UserKnownHostsFile to it, GlobalKnownHostsFile to /dev/null,
StrictHostKeyChecking yes, and UpdateHostKeys no (a host must not be able to add keys to it).

ROLLBACK. A node's Store checks its chain against its TPM. An administrator's workstation has no such
anchor, so current() takes the chain AND the lowest epoch the administrator will accept: the epoch of
the last manifest they saw, or of the revocation they are acting on. An older chain, on which a retired
node is still listed as live, is refused. There is no default.
"""
import argparse
import base64
import ipaddress
import os
import re
import sys
import tempfile

from deploy.baremetal import membership

Refused, require = membership.Refused, membership.require

KEY_TYPE = "ssh-ed25519"
_BLOB_PREFIX = len(KEY_TYPE).to_bytes(4, "big") + KEY_TYPE.encode() + (32).to_bytes(4, "big")


def host_key(ssh_host_pub):
    """The OpenSSH form of a manifest's ssh_host_pub: "ssh-ed25519 <base64>"."""
    membership.hex_field(ssh_host_pub, 64, "ssh_host_pub")
    return "%s %s" % (KEY_TYPE, base64.b64encode(_BLOB_PREFIX + bytes.fromhex(ssh_host_pub)).decode())


def raw_host_key(line):
    """The manifest form (64 hex) of an OpenSSH Ed25519 public key line, as in ssh_host_ed25519_key.pub:
    "ssh-ed25519 <base64> [comment]". Any other key type or length is refused. (51 bytes are 68 base64
    characters with no padding, so one key has one spelling.)"""
    require(isinstance(line, str), "an SSH public key is a line of text")
    fields = line.split()
    require(len(fields) >= 2 and fields[0] == KEY_TYPE, "the SSH host key must be %s" % KEY_TYPE)
    try:
        blob = base64.b64decode(fields[1], validate=True)
    except ValueError:
        raise Refused("the SSH host key is not base64")
    require(len(blob) == len(_BLOB_PREFIX) + 32 and blob.startswith(_BLOB_PREFIX), "the SSH host key is not a canonical %s key" % KEY_TYPE)
    return blob[len(_BLOB_PREFIX):].hex()


def known_hosts(manifest):
    """The known_hosts text for a v2 manifest (see the module docstring). Deterministic."""
    nodes = membership.validate(manifest)
    require(manifest["schema"] == membership.SCHEMA_V2, "a %s manifest names no SSH host keys: the chain must have moved to %s"
            % (manifest["schema"], membership.SCHEMA_V2))
    note = "regalia-kms epoch %d" % manifest["epoch"]
    lines = ["# Generated by deploy/baremetal/ssh_trust.py from membership epoch %d, manifest %s. Do not edit by hand."
             % (manifest["epoch"], membership.digest(manifest))]
    for node_id in sorted(nodes):
        node = nodes[node_id]
        if node["state"] not in membership.TERMINAL:
            lines.append("%s %s %s %s" % (node_id, host_key(node["ssh_host_pub"]), note, node["state"]))
    for node_id in sorted(nodes):
        node = nodes[node_id]
        if node["state"] in membership.TERMINAL and "ssh_host_pub" in node:
            lines.append("@revoked * %s %s %s %s" % (host_key(node["ssh_host_pub"]), note, node_id, node["state"]))
    return "\n".join(lines) + "\n"


def _plain_path(path, label):
    # an ssh_config value: no spaces, quotes, tokens (%h) or ~ expansion to reason about
    require(isinstance(path, str) and re.fullmatch(r"/[A-Za-z0-9_./-]{1,255}", path) is not None and "/../" not in path + "/",
            "%s must be an absolute path of letters, digits and . _ - /" % label)


def ssh_config(manifest, addresses, known_hosts_path, port=22):
    """An ssh_config fragment: one `Host <node_id>` per node that is not retired and has an address in
    `addresses` ({node_id: IPv4 address}; the manifest holds no addresses). Each host is checked against
    the generated known_hosts only, under the node's own name."""
    nodes = membership.validate(manifest)
    require(manifest["schema"] == membership.SCHEMA_V2, "a %s manifest names no SSH host keys" % manifest["schema"])
    _plain_path(known_hosts_path, "the known_hosts path")
    require(isinstance(port, int) and not isinstance(port, bool) and 1 <= port <= 65535, "the SSH port must be 1 to 65535")
    require(isinstance(addresses, dict), "addresses must map node IDs to IPv4 addresses")
    for node_id, address in addresses.items():
        require(node_id in nodes, "%r has an address but is not in the manifest" % (node_id,))
        require(nodes[node_id]["state"] not in membership.TERMINAL, "%s is %s: it gets no ssh_config entry" % (node_id, nodes[node_id]["state"]))
        try:
            require(str(ipaddress.IPv4Address(address)) == address, "the address of %s must be a plain IPv4 address" % node_id)
        except ValueError:
            raise Refused("the address of %s must be a plain IPv4 address" % node_id)
    require(len(set(addresses.values())) == len(addresses), "two nodes cannot have one address")
    out = ["# Generated by deploy/baremetal/ssh_trust.py from membership epoch %d, manifest %s. Do not edit by hand."
           % (manifest["epoch"], membership.digest(manifest))]
    for node_id in sorted(addresses):
        out += ["Host %s" % node_id,
                "    HostName %s" % addresses[node_id],
                "    Port %d" % port,
                "    HostKeyAlias %s" % node_id,
                "    HostKeyAlgorithms %s" % KEY_TYPE,
                "    UserKnownHostsFile %s" % known_hosts_path,
                "    GlobalKnownHostsFile /dev/null",
                "    StrictHostKeyChecking yes",
                "    UpdateHostKeys no",
                "    CheckHostIP no",
                "    ForwardAgent no"]
    return "\n".join(out) + "\n"


def current(envelopes, root_key, at_least_epoch):
    """The newest manifest of a whole chain, verified from the pinned root at epoch 1, and refused if it is
    older than `at_least_epoch` (the rollback check a workstation has instead of a TPM)."""
    require(isinstance(at_least_epoch, int) and not isinstance(at_least_epoch, bool) and at_least_epoch >= 1, "at_least_epoch must be an integer >= 1")
    require(isinstance(envelopes, list) and envelopes, "a chain is a non-empty list of envelopes")
    manifest = None
    for envelope in envelopes:
        nxt = membership.accept(manifest, envelope, root_key)
        require(nxt is not manifest, "the chain repeats epoch %d" % nxt["epoch"])
        manifest = nxt
    require(manifest["epoch"] >= at_least_epoch, "ROLLBACK: the chain ends at epoch %d and at least epoch %d is expected: "
            "fetch the current chain" % (manifest["epoch"], at_least_epoch))
    return manifest


def _write(path, text):
    directory = os.path.dirname(os.path.abspath(path))
    fd, tmp = tempfile.mkstemp(prefix=".regalia-ssh-", dir=directory)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--chain", required=True, help="the whole membership chain (a JSON list of envelopes, as Store keeps it)")
    ap.add_argument("--root-key", required=True, help="the pinned membership root key, 64 hex")
    ap.add_argument("--at-least-epoch", required=True, type=int, help="refuse a chain that ends below this epoch")
    ap.add_argument("--known-hosts", required=True, help="where to write the known_hosts file")
    ap.add_argument("--addresses", help="a JSON object {node_id: IPv4 address}; needed for --ssh-config")
    ap.add_argument("--ssh-config", help="where to write the ssh_config fragment")
    ap.add_argument("--port", type=int, default=22)
    args = ap.parse_args(argv)
    try:
        require((args.addresses is None) == (args.ssh_config is None), "--addresses and --ssh-config go together")
        with open(args.chain, "rb") as f:
            chain = membership.load(f.read(membership.MAX_CHAIN_BYTES + 1), limit=membership.MAX_CHAIN_BYTES)
        manifest = current(chain, args.root_key, args.at_least_epoch)
        hosts = known_hosts(manifest)
        config = None
        if args.ssh_config:
            with open(args.addresses, "rb") as f:
                addresses = membership.load(f.read(membership.MAX_BYTES + 1))
            config = ssh_config(manifest, addresses, os.path.abspath(args.known_hosts), args.port)
        _write(args.known_hosts, hosts)            # nothing is written unless everything was accepted
        if config is not None:
            _write(args.ssh_config, config)
    except (OSError, Refused) as failure:
        print("ssh_trust: %s" % failure, file=sys.stderr)
        return 1
    lines = hosts.splitlines()[1:]
    revoked = sum(1 for line in lines if line.startswith("@revoked"))
    print("ssh_trust: epoch %d, manifest %s: %d host(s), %d revoked key(s)"
          % (manifest["epoch"], membership.digest(manifest), len(lines) - revoked, revoked))
    return 0


if __name__ == "__main__":
    sys.exit(main())
